[{ "city": "Palatine", "state": "Illinois" },
{ "city": "San Diego", "state": "California" },
{ "city": "Arlington", "state": "Virginia" },
{ "city": "Delray Beach", "state": "Florida" },
{ "city": "Baltimore", "state": "Maryland" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Des Moines", "state": "Iowa" },
{ "city": "Olympia", "state": "Washington" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "Philadelphia", "state": "Pennsylvania" },
{ "city": "Rochester", "state": "New York" },
{ "city": "Mc Keesport", "state": "Pennsylvania" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "San Francisco", "state": "California" },
{ "city": "Garden Grove", "state": "California" },
{ "city": "Orlando", "state": "Florida" },
{ "city": "Tucson", "state": "Arizona" },
{ "city": "Columbia", "state": "South Carolina" },
{ "city": "Naples", "state": "Florida" },
{ "city": "Irvine", "state": "California" },
{ "city": "Duluth", "state": "Georgia" },
{ "city": "Columbus", "state": "Georgia" },
{ "city": "Kansas City", "state": "Missouri" },
{ "city": "Fort Myers", "state": "Florida" },
{ "city": "Rochester", "state": "New York" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Grand Rapids", "state": "Michigan" },
{ "city": "Boston", "state": "Massachusetts" },
{ "city": "Indianapolis", "state": "Indiana" },
{ "city": "Orlando", "state": "Florida" },
{ "city": "Providence", "state": "Rhode Island" },
{ "city": "Henderson", "state": "Nevada" },
{ "city": "Green Bay", "state": "Wisconsin" },
{ "city": "Albany", "state": "New York" },
{ "city": "New York City", "state": "New York" },
{ "city": "Charlottesville", "state": "Virginia" },
{ "city": "Nashville", "state": "Tennessee" },
{ "city": "Wilmington", "state": "Delaware" },
{ "city": "Tampa", "state": "Florida" },
{ "city": "Boynton Beach", "state": "Florida" },
{ "city": "Denton", "state": "Texas" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Las Vegas", "state": "Nevada" },
{ "city": "Durham", "state": "North Carolina" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Knoxville", "state": "Tennessee" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Abilene", "state": "Texas" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "Birmingham", "state": "Alabama" },
{ "city": "Oklahoma City", "state": "Oklahoma" },
{ "city": "Hollywood", "state": "Florida" },
{ "city": "New Haven", "state": "Connecticut" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Denver", "state": "Colorado" },
{ "city": "Columbia", "state": "South Carolina" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Jamaica", "state": "New York" },
{ "city": "Norfolk", "state": "Virginia" },
{ "city": "Los Angeles", "state": "California" },
{ "city": "South Lake Tahoe", "state": "California" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "Louisville", "state": "Kentucky" },
{ "city": "Boston", "state": "Massachusetts" },
{ "city": "Philadelphia", "state": "Pennsylvania" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Boca Raton", "state": "Florida" },
{ "city": "Austin", "state": "Texas" },
{ "city": "Watertown", "state": "Massachusetts" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Philadelphia", "state": "Pennsylvania" },
{ "city": "Orange", "state": "California" },
{ "city": "Boca Raton", "state": "Florida" },
{ "city": "Rochester", "state": "New York" },
{ "city": "Birmingham", "state": "Alabama" },
{ "city": "Jeffersonville", "state": "Indiana" },
{ "city": "Pensacola", "state": "Florida" },
{ "city": "Mobile", "state": "Alabama" },
{ "city": "Schenectady", "state": "New York" },
{ "city": "Des Moines", "state": "Iowa" },
{ "city": "Corpus Christi", "state": "Texas" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Omaha", "state": "Nebraska" },
{ "city": "Sacramento", "state": "California" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Reno", "state": "Nevada" },
{ "city": "Durham", "state": "North Carolina" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Lynn", "state": "Massachusetts" },
{ "city": "Myrtle Beach", "state": "South Carolina" },
{ "city": "Knoxville", "state": "Tennessee" },
{ "city": "Merrifield", "state": "Virginia" },
{ "city": "Sacramento", "state": "California" },
{ "city": "Santa Barbara", "state": "California" },
{ "city": "Falls Church", "state": "Virginia" },
{ "city": "Shreveport", "state": "Louisiana" },
{ "city": "Alexandria", "state": "Virginia" },
{ "city": "New Orleans", "state": "Louisiana" },
{ "city": "Torrance", "state": "California" },
{ "city": "Chattanooga", "state": "Tennessee" },
{ "city": "Louisville", "state": "Kentucky" },
{ "city": "Aurora", "state": "Colorado" },
{ "city": "South Bend", "state": "Indiana" },
{ "city": "San Diego", "state": "California" },
{ "city": "Young America", "state": "Minnesota" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Paterson", "state": "New Jersey" },
{ "city": "Bonita Springs", "state": "Florida" },
{ "city": "South Lake Tahoe", "state": "California" },
{ "city": "Peoria", "state": "Illinois" },
{ "city": "Trenton", "state": "New Jersey" },
{ "city": "Tampa", "state": "Florida" },
{ "city": "Spokane", "state": "Washington" },
{ "city": "Wilmington", "state": "North Carolina" },
{ "city": "Newark", "state": "New Jersey" },
{ "city": "Oxnard", "state": "California" },
{ "city": "Ocala", "state": "Florida" },
{ "city": "Gainesville", "state": "Florida" },
{ "city": "Duluth", "state": "Minnesota" },
{ "city": "Gilbert", "state": "Arizona" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "Richmond", "state": "Virginia" },
{ "city": "Jamaica", "state": "New York" },
{ "city": "Huntington Beach", "state": "California" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Vancouver", "state": "Washington" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "New York City", "state": "New York" },
{ "city": "Denver", "state": "Colorado" },
{ "city": "North Las Vegas", "state": "Nevada" },
{ "city": "Fort Worth", "state": "Texas" },
{ "city": "Garden Grove", "state": "California" },
{ "city": "Brooklyn", "state": "New York" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Miami", "state": "Florida" },
{ "city": "San Diego", "state": "California" },
{ "city": "Cambridge", "state": "Massachusetts" },
{ "city": "Sacramento", "state": "California" },
{ "city": "Jersey City", "state": "New Jersey" },
{ "city": "Birmingham", "state": "Alabama" },
{ "city": "Birmingham", "state": "Alabama" },
{ "city": "Albany", "state": "New York" },
{ "city": "Scranton", "state": "Pennsylvania" },
{ "city": "Philadelphia", "state": "Pennsylvania" },
{ "city": "Green Bay", "state": "Wisconsin" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Mesa", "state": "Arizona" },
{ "city": "Jeffersonville", "state": "Indiana" },
{ "city": "Long Beach", "state": "California" },
{ "city": "Montgomery", "state": "Alabama" },
{ "city": "Salt Lake City", "state": "Utah" },
{ "city": "San Francisco", "state": "California" },
{ "city": "Redwood City", "state": "California" },
{ "city": "Baton Rouge", "state": "Louisiana" },
{ "city": "Young America", "state": "Minnesota" },
{ "city": "Fort Collins", "state": "Colorado" },
{ "city": "Frankfort", "state": "Kentucky" },
{ "city": "Fort Wayne", "state": "Indiana" },
{ "city": "Lubbock", "state": "Texas" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Indianapolis", "state": "Indiana" },
{ "city": "White Plains", "state": "New York" },
{ "city": "Burbank", "state": "California" },
{ "city": "Tucson", "state": "Arizona" },
{ "city": "Laredo", "state": "Texas" },
{ "city": "Schenectady", "state": "New York" },
{ "city": "Newton", "state": "Massachusetts" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "Young America", "state": "Minnesota" },
{ "city": "Philadelphia", "state": "Pennsylvania" },
{ "city": "Bozeman", "state": "Montana" },
{ "city": "Monticello", "state": "Minnesota" },
{ "city": "Pittsburgh", "state": "Pennsylvania" },
{ "city": "Vancouver", "state": "Washington" },
{ "city": "Philadelphia", "state": "Pennsylvania" },
{ "city": "Amarillo", "state": "Texas" },
{ "city": "Nashville", "state": "Tennessee" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Shawnee Mission", "state": "Kansas" },
{ "city": "Winston Salem", "state": "North Carolina" },
{ "city": "Monticello", "state": "Minnesota" },
{ "city": "Louisville", "state": "Kentucky" },
{ "city": "Richmond", "state": "Virginia" },
{ "city": "Tacoma", "state": "Washington" },
{ "city": "Greensboro", "state": "North Carolina" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Birmingham", "state": "Alabama" },
{ "city": "Anchorage", "state": "Alaska" },
{ "city": "Birmingham", "state": "Alabama" },
{ "city": "Akron", "state": "Ohio" },
{ "city": "Anchorage", "state": "Alaska" },
{ "city": "Fort Worth", "state": "Texas" },
{ "city": "Panama City", "state": "Florida" },
{ "city": "Raleigh", "state": "North Carolina" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Clearwater", "state": "Florida" },
{ "city": "Fort Lauderdale", "state": "Florida" },
{ "city": "Oklahoma City", "state": "Oklahoma" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "Oklahoma City", "state": "Oklahoma" },
{ "city": "Lakewood", "state": "Washington" },
{ "city": "Jacksonville", "state": "Florida" },
{ "city": "South Bend", "state": "Indiana" },
{ "city": "Garden Grove", "state": "California" },
{ "city": "Sacramento", "state": "California" },
{ "city": "Akron", "state": "Ohio" },
{ "city": "Portland", "state": "Maine" },
{ "city": "Detroit", "state": "Michigan" },
{ "city": "Peoria", "state": "Illinois" },
{ "city": "Rochester", "state": "New York" },
{ "city": "Trenton", "state": "New Jersey" },
{ "city": "Oklahoma City", "state": "Oklahoma" },
{ "city": "Chula Vista", "state": "California" },
{ "city": "Littleton", "state": "Colorado" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "Boise", "state": "Idaho" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Los Angeles", "state": "California" },
{ "city": "Fort Worth", "state": "Texas" },
{ "city": "Colorado Springs", "state": "Colorado" },
{ "city": "Garland", "state": "Texas" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Seattle", "state": "Washington" },
{ "city": "Denver", "state": "Colorado" },
{ "city": "Portland", "state": "Maine" },
{ "city": "Boise", "state": "Idaho" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Las Vegas", "state": "Nevada" },
{ "city": "Dayton", "state": "Ohio" },
{ "city": "Detroit", "state": "Michigan" },
{ "city": "Honolulu", "state": "Hawaii" },
{ "city": "Santa Ana", "state": "California" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Macon", "state": "Georgia" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Omaha", "state": "Nebraska" },
{ "city": "Richmond", "state": "Virginia" },
{ "city": "Midland", "state": "Texas" },
{ "city": "Miami", "state": "Florida" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Denton", "state": "Texas" },
{ "city": "Austin", "state": "Texas" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Norwalk", "state": "Connecticut" },
{ "city": "Camden", "state": "New Jersey" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Sacramento", "state": "California" },
{ "city": "Muncie", "state": "Indiana" },
{ "city": "Orlando", "state": "Florida" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Miami", "state": "Florida" },
{ "city": "Kansas City", "state": "Kansas" },
{ "city": "Syracuse", "state": "New York" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "San Francisco", "state": "California" },
{ "city": "Evansville", "state": "Indiana" },
{ "city": "Rochester", "state": "New York" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Arlington", "state": "Virginia" },
{ "city": "Trenton", "state": "New Jersey" },
{ "city": "San Angelo", "state": "Texas" },
{ "city": "Huntsville", "state": "Texas" },
{ "city": "Manassas", "state": "Virginia" },
{ "city": "Albuquerque", "state": "New Mexico" },
{ "city": "Portland", "state": "Oregon" },
{ "city": "Juneau", "state": "Alaska" },
{ "city": "Lees Summit", "state": "Missouri" },
{ "city": "Albuquerque", "state": "New Mexico" },
{ "city": "Warren", "state": "Michigan" },
{ "city": "Baton Rouge", "state": "Louisiana" },
{ "city": "Fresno", "state": "California" },
{ "city": "Shawnee Mission", "state": "Kansas" },
{ "city": "Shreveport", "state": "Louisiana" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Aiken", "state": "South Carolina" },
{ "city": "Anchorage", "state": "Alaska" },
{ "city": "Roanoke", "state": "Virginia" },
{ "city": "Minneapolis", "state": "Minnesota" },
{ "city": "Minneapolis", "state": "Minnesota" },
{ "city": "Roanoke", "state": "Virginia" },
{ "city": "Lexington", "state": "Kentucky" },
{ "city": "Fargo", "state": "North Dakota" },
{ "city": "Van Nuys", "state": "California" },
{ "city": "New Orleans", "state": "Louisiana" },
{ "city": "Jacksonville", "state": "Florida" },
{ "city": "Vancouver", "state": "Washington" },
{ "city": "Las Vegas", "state": "Nevada" },
{ "city": "Grand Rapids", "state": "Michigan" },
{ "city": "Columbia", "state": "South Carolina" },
{ "city": "Stockton", "state": "California" },
{ "city": "Clearwater", "state": "Florida" },
{ "city": "Tallahassee", "state": "Florida" },
{ "city": "Springfield", "state": "Massachusetts" },
{ "city": "Tallahassee", "state": "Florida" },
{ "city": "Northridge", "state": "California" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Fresno", "state": "California" },
{ "city": "Baton Rouge", "state": "Louisiana" },
{ "city": "Panama City", "state": "Florida" },
{ "city": "Toledo", "state": "Ohio" },
{ "city": "Fort Smith", "state": "Arkansas" },
{ "city": "Springfield", "state": "Illinois" },
{ "city": "Greenville", "state": "South Carolina" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Minneapolis", "state": "Minnesota" },
{ "city": "Columbus", "state": "Ohio" },
{ "city": "Amarillo", "state": "Texas" },
{ "city": "Miami", "state": "Florida" },
{ "city": "Humble", "state": "Texas" },
{ "city": "Mesa", "state": "Arizona" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Delray Beach", "state": "Florida" },
{ "city": "Oklahoma City", "state": "Oklahoma" },
{ "city": "Fredericksburg", "state": "Virginia" },
{ "city": "Huntington", "state": "West Virginia" },
{ "city": "Flushing", "state": "New York" },
{ "city": "Palo Alto", "state": "California" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Las Vegas", "state": "Nevada" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Hartford", "state": "Connecticut" },
{ "city": "Irvine", "state": "California" },
{ "city": "Pittsburgh", "state": "Pennsylvania" },
{ "city": "New York City", "state": "New York" },
{ "city": "Youngstown", "state": "Ohio" },
{ "city": "Flint", "state": "Michigan" },
{ "city": "Austin", "state": "Texas" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Reston", "state": "Virginia" },
{ "city": "Bonita Springs", "state": "Florida" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Santa Ana", "state": "California" },
{ "city": "Birmingham", "state": "Alabama" },
{ "city": "West Palm Beach", "state": "Florida" },
{ "city": "Bronx", "state": "New York" },
{ "city": "Port Charlotte", "state": "Florida" },
{ "city": "Fort Worth", "state": "Texas" },
{ "city": "Wilmington", "state": "Delaware" },
{ "city": "Kansas City", "state": "Missouri" },
{ "city": "Davenport", "state": "Iowa" },
{ "city": "Jamaica", "state": "New York" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Amarillo", "state": "Texas" },
{ "city": "Colorado Springs", "state": "Colorado" },
{ "city": "Fresno", "state": "California" },
{ "city": "Indianapolis", "state": "Indiana" },
{ "city": "Colorado Springs", "state": "Colorado" },
{ "city": "New York City", "state": "New York" },
{ "city": "Corona", "state": "California" },
{ "city": "Richmond", "state": "California" },
{ "city": "New York City", "state": "New York" },
{ "city": "Boulder", "state": "Colorado" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Salt Lake City", "state": "Utah" },
{ "city": "Fort Wayne", "state": "Indiana" },
{ "city": "Omaha", "state": "Nebraska" },
{ "city": "Boston", "state": "Massachusetts" },
{ "city": "Greensboro", "state": "North Carolina" },
{ "city": "Amarillo", "state": "Texas" },
{ "city": "Amarillo", "state": "Texas" },
{ "city": "Des Moines", "state": "Iowa" },
{ "city": "North Hollywood", "state": "California" },
{ "city": "Honolulu", "state": "Hawaii" },
{ "city": "Florence", "state": "South Carolina" },
{ "city": "Pasadena", "state": "California" },
{ "city": "Denver", "state": "Colorado" },
{ "city": "New York City", "state": "New York" },
{ "city": "Boston", "state": "Massachusetts" },
{ "city": "Indianapolis", "state": "Indiana" },
{ "city": "Bloomington", "state": "Indiana" },
{ "city": "Eugene", "state": "Oregon" },
{ "city": "Bakersfield", "state": "California" },
{ "city": "San Francisco", "state": "California" },
{ "city": "Saint Paul", "state": "Minnesota" },
{ "city": "Kent", "state": "Washington" },
{ "city": "Portland", "state": "Oregon" },
{ "city": "Grand Rapids", "state": "Michigan" },
{ "city": "Scranton", "state": "Pennsylvania" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Henderson", "state": "Nevada" },
{ "city": "New York City", "state": "New York" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Sacramento", "state": "California" },
{ "city": "Duluth", "state": "Georgia" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Fort Wayne", "state": "Indiana" },
{ "city": "Lancaster", "state": "Pennsylvania" },
{ "city": "Fort Wayne", "state": "Indiana" },
{ "city": "Baltimore", "state": "Maryland" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Greenville", "state": "South Carolina" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Mount Vernon", "state": "New York" },
{ "city": "Vancouver", "state": "Washington" },
{ "city": "Anaheim", "state": "California" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Inglewood", "state": "California" },
{ "city": "Lincoln", "state": "Nebraska" },
{ "city": "Miami", "state": "Florida" },
{ "city": "Columbus", "state": "Ohio" },
{ "city": "Monroe", "state": "Louisiana" },
{ "city": "Oakland", "state": "California" },
{ "city": "Detroit", "state": "Michigan" },
{ "city": "Canton", "state": "Ohio" },
{ "city": "Hartford", "state": "Connecticut" },
{ "city": "Detroit", "state": "Michigan" },
{ "city": "Baltimore", "state": "Maryland" },
{ "city": "Saint Paul", "state": "Minnesota" },
{ "city": "Birmingham", "state": "Alabama" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Miami", "state": "Florida" },
{ "city": "Cleveland", "state": "Ohio" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Berkeley", "state": "California" },
{ "city": "Lakewood", "state": "Washington" },
{ "city": "Tucson", "state": "Arizona" },
{ "city": "Fort Worth", "state": "Texas" },
{ "city": "Wilmington", "state": "Delaware" },
{ "city": "Decatur", "state": "Georgia" },
{ "city": "Everett", "state": "Washington" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Rockford", "state": "Illinois" },
{ "city": "North Hollywood", "state": "California" },
{ "city": "Saint Paul", "state": "Minnesota" },
{ "city": "New Castle", "state": "Pennsylvania" },
{ "city": "Biloxi", "state": "Mississippi" },
{ "city": "Vero Beach", "state": "Florida" },
{ "city": "Santa Clara", "state": "California" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Richmond", "state": "Virginia" },
{ "city": "Philadelphia", "state": "Pennsylvania" },
{ "city": "New York City", "state": "New York" },
{ "city": "Omaha", "state": "Nebraska" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Vero Beach", "state": "Florida" },
{ "city": "New York City", "state": "New York" },
{ "city": "San Francisco", "state": "California" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Huntington", "state": "West Virginia" },
{ "city": "Virginia Beach", "state": "Virginia" },
{ "city": "Winston Salem", "state": "North Carolina" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "New Orleans", "state": "Louisiana" },
{ "city": "Denver", "state": "Colorado" },
{ "city": "Brooklyn", "state": "New York" },
{ "city": "Spokane", "state": "Washington" },
{ "city": "Memphis", "state": "Tennessee" },
{ "city": "Rochester", "state": "Minnesota" },
{ "city": "Orlando", "state": "Florida" },
{ "city": "Newark", "state": "Delaware" },
{ "city": "Fort Worth", "state": "Texas" },
{ "city": "Grand Rapids", "state": "Michigan" },
{ "city": "San Diego", "state": "California" },
{ "city": "Des Moines", "state": "Iowa" },
{ "city": "New York City", "state": "New York" },
{ "city": "Indianapolis", "state": "Indiana" },
{ "city": "Raleigh", "state": "North Carolina" },
{ "city": "Conroe", "state": "Texas" },
{ "city": "Saint Louis", "state": "Missouri" },
{ "city": "Madison", "state": "Wisconsin" },
{ "city": "Spokane", "state": "Washington" },
{ "city": "Tucson", "state": "Arizona" },
{ "city": "Nashville", "state": "Tennessee" },
{ "city": "Santa Clara", "state": "California" },
{ "city": "Trenton", "state": "New Jersey" },
{ "city": "Brooklyn", "state": "New York" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Fort Lauderdale", "state": "Florida" },
{ "city": "Birmingham", "state": "Alabama" },
{ "city": "Long Beach", "state": "California" },
{ "city": "Asheville", "state": "North Carolina" },
{ "city": "Lynchburg", "state": "Virginia" },
{ "city": "Cleveland", "state": "Ohio" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "Bakersfield", "state": "California" },
{ "city": "Lehigh Acres", "state": "Florida" },
{ "city": "Denver", "state": "Colorado" },
{ "city": "Corpus Christi", "state": "Texas" },
{ "city": "Chattanooga", "state": "Tennessee" },
{ "city": "Seattle", "state": "Washington" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Warren", "state": "Ohio" },
{ "city": "Scottsdale", "state": "Arizona" },
{ "city": "Fort Lauderdale", "state": "Florida" },
{ "city": "Gainesville", "state": "Georgia" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Myrtle Beach", "state": "South Carolina" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Erie", "state": "Pennsylvania" },
{ "city": "Omaha", "state": "Nebraska" },
{ "city": "Dearborn", "state": "Michigan" },
{ "city": "Grand Junction", "state": "Colorado" },
{ "city": "Billings", "state": "Montana" },
{ "city": "New York City", "state": "New York" },
{ "city": "Huntsville", "state": "Texas" },
{ "city": "Tucson", "state": "Arizona" },
{ "city": "Tucson", "state": "Arizona" },
{ "city": "New Haven", "state": "Connecticut" },
{ "city": "Kansas City", "state": "Kansas" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "San Antonio", "state": "Texas" },
{ "city": "Toledo", "state": "Ohio" },
{ "city": "Albuquerque", "state": "New Mexico" },
{ "city": "Shreveport", "state": "Louisiana" },
{ "city": "Marietta", "state": "Georgia" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Richmond", "state": "Virginia" },
{ "city": "Omaha", "state": "Nebraska" },
{ "city": "Roanoke", "state": "Virginia" },
{ "city": "Riverside", "state": "California" },
{ "city": "Richmond", "state": "Virginia" },
{ "city": "Asheville", "state": "North Carolina" },
{ "city": "Albuquerque", "state": "New Mexico" },
{ "city": "Shreveport", "state": "Louisiana" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Gainesville", "state": "Florida" },
{ "city": "New Haven", "state": "Connecticut" },
{ "city": "Saint Louis", "state": "Missouri" },
{ "city": "Boca Raton", "state": "Florida" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Milwaukee", "state": "Wisconsin" },
{ "city": "Sparks", "state": "Nevada" },
{ "city": "Peoria", "state": "Illinois" },
{ "city": "Columbus", "state": "Mississippi" },
{ "city": "Grand Junction", "state": "Colorado" },
{ "city": "New Haven", "state": "Connecticut" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Pueblo", "state": "Colorado" },
{ "city": "Hartford", "state": "Connecticut" },
{ "city": "Detroit", "state": "Michigan" },
{ "city": "Hollywood", "state": "Florida" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "Decatur", "state": "Georgia" },
{ "city": "Naperville", "state": "Illinois" },
{ "city": "San Antonio", "state": "Texas" },
{ "city": "Des Moines", "state": "Iowa" },
{ "city": "Madison", "state": "Wisconsin" },
{ "city": "New Haven", "state": "Connecticut" },
{ "city": "Hot Springs National Park", "state": "Arkansas" },
{ "city": "Riverside", "state": "California" },
{ "city": "Long Beach", "state": "California" },
{ "city": "Pensacola", "state": "Florida" },
{ "city": "Amarillo", "state": "Texas" },
{ "city": "San Francisco", "state": "California" },
{ "city": "Annapolis", "state": "Maryland" },
{ "city": "Long Beach", "state": "California" },
{ "city": "Lynchburg", "state": "Virginia" },
{ "city": "Fresno", "state": "California" },
{ "city": "Watertown", "state": "Massachusetts" },
{ "city": "Fort Worth", "state": "Texas" },
{ "city": "Little Rock", "state": "Arkansas" },
{ "city": "Springfield", "state": "Illinois" },
{ "city": "Sioux Falls", "state": "South Dakota" },
{ "city": "Vero Beach", "state": "Florida" },
{ "city": "Salt Lake City", "state": "Utah" },
{ "city": "New York City", "state": "New York" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Pittsburgh", "state": "Pennsylvania" },
{ "city": "Montgomery", "state": "Alabama" },
{ "city": "Denver", "state": "Colorado" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Baltimore", "state": "Maryland" },
{ "city": "San Francisco", "state": "California" },
{ "city": "New Orleans", "state": "Louisiana" },
{ "city": "Minneapolis", "state": "Minnesota" },
{ "city": "Hot Springs National Park", "state": "Arkansas" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Lubbock", "state": "Texas" },
{ "city": "Boulder", "state": "Colorado" },
{ "city": "Bonita Springs", "state": "Florida" },
{ "city": "San Antonio", "state": "Texas" },
{ "city": "Baton Rouge", "state": "Louisiana" },
{ "city": "West Palm Beach", "state": "Florida" },
{ "city": "Denver", "state": "Colorado" },
{ "city": "Kansas City", "state": "Missouri" },
{ "city": "Minneapolis", "state": "Minnesota" },
{ "city": "Green Bay", "state": "Wisconsin" },
{ "city": "Rochester", "state": "New York" },
{ "city": "Richmond", "state": "Virginia" },
{ "city": "Philadelphia", "state": "Pennsylvania" },
{ "city": "Minneapolis", "state": "Minnesota" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "Terre Haute", "state": "Indiana" },
{ "city": "Hampton", "state": "Virginia" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Fort Lauderdale", "state": "Florida" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Annapolis", "state": "Maryland" },
{ "city": "Brooklyn", "state": "New York" },
{ "city": "San Jose", "state": "California" },
{ "city": "Fresno", "state": "California" },
{ "city": "Jefferson City", "state": "Missouri" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Glendale", "state": "Arizona" },
{ "city": "Garden Grove", "state": "California" },
{ "city": "Charleston", "state": "West Virginia" },
{ "city": "Albany", "state": "New York" },
{ "city": "Corpus Christi", "state": "Texas" },
{ "city": "Orange", "state": "California" },
{ "city": "Tampa", "state": "Florida" },
{ "city": "Punta Gorda", "state": "Florida" },
{ "city": "Pittsburgh", "state": "Pennsylvania" },
{ "city": "Albany", "state": "New York" },
{ "city": "Mesquite", "state": "Texas" },
{ "city": "San Antonio", "state": "Texas" },
{ "city": "Sparks", "state": "Nevada" },
{ "city": "Sacramento", "state": "California" },
{ "city": "Raleigh", "state": "North Carolina" },
{ "city": "Muskegon", "state": "Michigan" },
{ "city": "Milwaukee", "state": "Wisconsin" },
{ "city": "Chattanooga", "state": "Tennessee" },
{ "city": "Harrisburg", "state": "Pennsylvania" },
{ "city": "Fullerton", "state": "California" },
{ "city": "Detroit", "state": "Michigan" },
{ "city": "Roanoke", "state": "Virginia" },
{ "city": "Pasadena", "state": "California" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Springfield", "state": "Illinois" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Frederick", "state": "Maryland" },
{ "city": "Miami", "state": "Florida" },
{ "city": "Norfolk", "state": "Virginia" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "Portland", "state": "Oregon" },
{ "city": "Virginia Beach", "state": "Virginia" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Topeka", "state": "Kansas" },
{ "city": "Seattle", "state": "Washington" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Las Vegas", "state": "Nevada" },
{ "city": "Albuquerque", "state": "New Mexico" },
{ "city": "Las Vegas", "state": "Nevada" },
{ "city": "Davenport", "state": "Iowa" },
{ "city": "Moreno Valley", "state": "California" },
{ "city": "Tacoma", "state": "Washington" },
{ "city": "San Bernardino", "state": "California" },
{ "city": "Kansas City", "state": "Missouri" },
{ "city": "Kansas City", "state": "Missouri" },
{ "city": "Lexington", "state": "Kentucky" },
{ "city": "Arvada", "state": "Colorado" },
{ "city": "Baton Rouge", "state": "Louisiana" },
{ "city": "Orlando", "state": "Florida" },
{ "city": "Saint Louis", "state": "Missouri" },
{ "city": "Boston", "state": "Massachusetts" },
{ "city": "Paterson", "state": "New Jersey" },
{ "city": "Topeka", "state": "Kansas" },
{ "city": "Kansas City", "state": "Missouri" },
{ "city": "Wichita", "state": "Kansas" },
{ "city": "Gadsden", "state": "Alabama" },
{ "city": "New Orleans", "state": "Louisiana" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "Peoria", "state": "Illinois" },
{ "city": "Saint Petersburg", "state": "Florida" },
{ "city": "London", "state": "Kentucky" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "Brooklyn", "state": "New York" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Madison", "state": "Wisconsin" },
{ "city": "Bradenton", "state": "Florida" },
{ "city": "Boise", "state": "Idaho" },
{ "city": "Boca Raton", "state": "Florida" },
{ "city": "Garden Grove", "state": "California" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Lincoln", "state": "Nebraska" },
{ "city": "Farmington", "state": "Michigan" },
{ "city": "Riverside", "state": "California" },
{ "city": "Lexington", "state": "Kentucky" },
{ "city": "Bakersfield", "state": "California" },
{ "city": "Orlando", "state": "Florida" },
{ "city": "Lakeland", "state": "Florida" },
{ "city": "Lakewood", "state": "Washington" },
{ "city": "Shreveport", "state": "Louisiana" },
{ "city": "Albany", "state": "New York" },
{ "city": "Lawrenceville", "state": "Georgia" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Lubbock", "state": "Texas" },
{ "city": "Scranton", "state": "Pennsylvania" },
{ "city": "Corpus Christi", "state": "Texas" },
{ "city": "Terre Haute", "state": "Indiana" },
{ "city": "White Plains", "state": "New York" },
{ "city": "Oklahoma City", "state": "Oklahoma" },
{ "city": "Columbus", "state": "Ohio" },
{ "city": "Iowa City", "state": "Iowa" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Springfield", "state": "Massachusetts" },
{ "city": "Sarasota", "state": "Florida" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Indianapolis", "state": "Indiana" },
{ "city": "Harrisburg", "state": "Pennsylvania" },
{ "city": "Dayton", "state": "Ohio" },
{ "city": "Newport News", "state": "Virginia" },
{ "city": "Montgomery", "state": "Alabama" },
{ "city": "Cleveland", "state": "Ohio" },
{ "city": "Kansas City", "state": "Kansas" },
{ "city": "Rochester", "state": "New York" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Tacoma", "state": "Washington" },
{ "city": "Arvada", "state": "Colorado" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "North Hollywood", "state": "California" },
{ "city": "Los Angeles", "state": "California" },
{ "city": "Toledo", "state": "Ohio" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Camden", "state": "New Jersey" },
{ "city": "Mobile", "state": "Alabama" },
{ "city": "Jamaica", "state": "New York" },
{ "city": "Montgomery", "state": "Alabama" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Burbank", "state": "California" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Fort Lauderdale", "state": "Florida" },
{ "city": "Memphis", "state": "Tennessee" },
{ "city": "Columbus", "state": "Ohio" },
{ "city": "Fort Lauderdale", "state": "Florida" },
{ "city": "Montgomery", "state": "Alabama" },
{ "city": "West Hartford", "state": "Connecticut" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Saint Louis", "state": "Missouri" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Los Angeles", "state": "California" },
{ "city": "Birmingham", "state": "Alabama" },
{ "city": "Anchorage", "state": "Alaska" },
{ "city": "Santa Barbara", "state": "California" },
{ "city": "Shawnee Mission", "state": "Kansas" },
{ "city": "Richmond", "state": "Virginia" },
{ "city": "Austin", "state": "Texas" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "Kingsport", "state": "Tennessee" },
{ "city": "Staten Island", "state": "New York" },
{ "city": "Boise", "state": "Idaho" },
{ "city": "Tallahassee", "state": "Florida" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Frederick", "state": "Maryland" },
{ "city": "Tacoma", "state": "Washington" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Richmond", "state": "California" },
{ "city": "Buffalo", "state": "New York" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Mobile", "state": "Alabama" },
{ "city": "San Jose", "state": "California" },
{ "city": "Temple", "state": "Texas" },
{ "city": "Los Angeles", "state": "California" },
{ "city": "Miami", "state": "Florida" },
{ "city": "Pompano Beach", "state": "Florida" },
{ "city": "Scottsdale", "state": "Arizona" },
{ "city": "Mesa", "state": "Arizona" },
{ "city": "Lake Charles", "state": "Louisiana" },
{ "city": "Huntsville", "state": "Alabama" },
{ "city": "Mesa", "state": "Arizona" },
{ "city": "Wilkes Barre", "state": "Pennsylvania" },
{ "city": "Salt Lake City", "state": "Utah" },
{ "city": "Shawnee Mission", "state": "Kansas" },
{ "city": "Gatesville", "state": "Texas" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Minneapolis", "state": "Minnesota" },
{ "city": "Naples", "state": "Florida" },
{ "city": "Pompano Beach", "state": "Florida" },
{ "city": "Amarillo", "state": "Texas" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Philadelphia", "state": "Pennsylvania" },
{ "city": "Santa Barbara", "state": "California" },
{ "city": "Wichita Falls", "state": "Texas" },
{ "city": "Austin", "state": "Texas" },
{ "city": "Des Moines", "state": "Iowa" },
{ "city": "San Diego", "state": "California" },
{ "city": "Fresno", "state": "California" },
{ "city": "Anchorage", "state": "Alaska" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Tampa", "state": "Florida" },
{ "city": "Houston", "state": "Texas" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Billings", "state": "Montana" },
{ "city": "Charleston", "state": "West Virginia" },
{ "city": "Miami Beach", "state": "Florida" },
{ "city": "Anchorage", "state": "Alaska" },
{ "city": "Young America", "state": "Minnesota" },
{ "city": "Austin", "state": "Texas" },
{ "city": "Sarasota", "state": "Florida" },
{ "city": "Mc Keesport", "state": "Pennsylvania" },
{ "city": "Lawrenceville", "state": "Georgia" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "San Antonio", "state": "Texas" },
{ "city": "Los Angeles", "state": "California" },
{ "city": "Colorado Springs", "state": "Colorado" },
{ "city": "Seattle", "state": "Washington" },
{ "city": "Oklahoma City", "state": "Oklahoma" },
{ "city": "Johnstown", "state": "Pennsylvania" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "San Diego", "state": "California" },
{ "city": "Arlington", "state": "Texas" },
{ "city": "Charleston", "state": "West Virginia" },
{ "city": "Santa Barbara", "state": "California" },
{ "city": "Norfolk", "state": "Virginia" },
{ "city": "Scottsdale", "state": "Arizona" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "Knoxville", "state": "Tennessee" },
{ "city": "Fayetteville", "state": "North Carolina" },
{ "city": "San Francisco", "state": "California" },
{ "city": "Greenville", "state": "South Carolina" },
{ "city": "New York City", "state": "New York" },
{ "city": "Indianapolis", "state": "Indiana" },
{ "city": "Jackson", "state": "Mississippi" },
{ "city": "Erie", "state": "Pennsylvania" },
{ "city": "Charleston", "state": "West Virginia" },
{ "city": "Saint Louis", "state": "Missouri" },
{ "city": "Sterling", "state": "Virginia" },
{ "city": "Pasadena", "state": "California" },
{ "city": "Reading", "state": "Pennsylvania" },
{ "city": "Saint Louis", "state": "Missouri" },
{ "city": "Bradenton", "state": "Florida" },
{ "city": "Gainesville", "state": "Georgia" },
{ "city": "Cambridge", "state": "Massachusetts" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Albuquerque", "state": "New Mexico" },
{ "city": "Scottsdale", "state": "Arizona" },
{ "city": "Boynton Beach", "state": "Florida" },
{ "city": "Troy", "state": "Michigan" },
{ "city": "Raleigh", "state": "North Carolina" },
{ "city": "Boston", "state": "Massachusetts" },
{ "city": "Pittsburgh", "state": "Pennsylvania" },
{ "city": "Seattle", "state": "Washington" },
{ "city": "Sarasota", "state": "Florida" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Albany", "state": "New York" },
{ "city": "Kansas City", "state": "Missouri" },
{ "city": "Chattanooga", "state": "Tennessee" },
{ "city": "Maple Plain", "state": "Minnesota" },
{ "city": "Seattle", "state": "Washington" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Hyattsville", "state": "Maryland" },
{ "city": "Peoria", "state": "Illinois" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Vancouver", "state": "Washington" },
{ "city": "Bethlehem", "state": "Pennsylvania" },
{ "city": "Omaha", "state": "Nebraska" },
{ "city": "Topeka", "state": "Kansas" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Huntsville", "state": "Alabama" },
{ "city": "Ventura", "state": "California" },
{ "city": "Los Angeles", "state": "California" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Gainesville", "state": "Georgia" },
{ "city": "Plano", "state": "Texas" },
{ "city": "Cincinnati", "state": "Ohio" },
{ "city": "Laurel", "state": "Maryland" },
{ "city": "Wilmington", "state": "Delaware" },
{ "city": "Springfield", "state": "Massachusetts" },
{ "city": "Philadelphia", "state": "Pennsylvania" },
{ "city": "Richmond", "state": "California" },
{ "city": "Orange", "state": "California" },
{ "city": "Augusta", "state": "Georgia" },
{ "city": "Tallahassee", "state": "Florida" },
{ "city": "Winter Haven", "state": "Florida" },
{ "city": "Long Beach", "state": "California" },
{ "city": "Burbank", "state": "California" },
{ "city": "Denver", "state": "Colorado" },
{ "city": "Sacramento", "state": "California" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Panama City", "state": "Florida" },
{ "city": "Miami", "state": "Florida" },
{ "city": "Detroit", "state": "Michigan" },
{ "city": "Roanoke", "state": "Virginia" },
{ "city": "Louisville", "state": "Kentucky" },
{ "city": "Erie", "state": "Pennsylvania" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Arvada", "state": "Colorado" },
{ "city": "Charleston", "state": "South Carolina" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Tucson", "state": "Arizona" },
{ "city": "Long Beach", "state": "California" },
{ "city": "Gainesville", "state": "Georgia" },
{ "city": "Redwood City", "state": "California" },
{ "city": "New York City", "state": "New York" },
{ "city": "Raleigh", "state": "North Carolina" },
{ "city": "Baton Rouge", "state": "Louisiana" },
{ "city": "Huntington", "state": "West Virginia" },
{ "city": "Las Vegas", "state": "Nevada" },
{ "city": "Los Angeles", "state": "California" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Kansas City", "state": "Missouri" },
{ "city": "Palatine", "state": "Illinois" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Madison", "state": "Wisconsin" },
{ "city": "San Antonio", "state": "Texas" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "Jacksonville", "state": "Florida" },
{ "city": "Huntington", "state": "West Virginia" },
{ "city": "Fort Collins", "state": "Colorado" },
{ "city": "Boston", "state": "Massachusetts" },
{ "city": "Norman", "state": "Oklahoma" },
{ "city": "Memphis", "state": "Tennessee" },
{ "city": "North Las Vegas", "state": "Nevada" },
{ "city": "Missoula", "state": "Montana" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Gaithersburg", "state": "Maryland" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Topeka", "state": "Kansas" },
{ "city": "Pittsburgh", "state": "Pennsylvania" },
{ "city": "Tulsa", "state": "Oklahoma" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Arlington", "state": "Texas" },
{ "city": "New York City", "state": "New York" },
{ "city": "London", "state": "Kentucky" },
{ "city": "Toledo", "state": "Ohio" },
{ "city": "Boston", "state": "Massachusetts" },
{ "city": "Tacoma", "state": "Washington" },
{ "city": "Charlotte", "state": "North Carolina" },
{ "city": "Kingsport", "state": "Tennessee" },
{ "city": "New York City", "state": "New York" },
{ "city": "Everett", "state": "Washington" },
{ "city": "Boston", "state": "Massachusetts" },
{ "city": "New York City", "state": "New York" },
{ "city": "Salt Lake City", "state": "Utah" },
{ "city": "Houston", "state": "Texas" },
{ "city": "Nashville", "state": "Tennessee" },
{ "city": "Saint Paul", "state": "Minnesota" },
{ "city": "Irvine", "state": "California" },
{ "city": "Denver", "state": "Colorado" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "Newark", "state": "New Jersey" },
{ "city": "Richmond", "state": "Virginia" },
{ "city": "Huntington", "state": "West Virginia" },
{ "city": "Shawnee Mission", "state": "Kansas" },
{ "city": "El Paso", "state": "Texas" },
{ "city": "Reno", "state": "Nevada" },
{ "city": "Salt Lake City", "state": "Utah" },
{ "city": "Indianapolis", "state": "Indiana" },
{ "city": "Austin", "state": "Texas" },
{ "city": "New York City", "state": "New York" },
{ "city": "Pensacola", "state": "Florida" },
{ "city": "Madison", "state": "Wisconsin" },
{ "city": "Washington", "state": "District of Columbia" },
{ "city": "Knoxville", "state": "Tennessee" },
{ "city": "Florence", "state": "South Carolina" },
{ "city": "Fresno", "state": "California" },
{ "city": "Pittsburgh", "state": "Pennsylvania" },
{ "city": "Baton Rouge", "state": "Louisiana" },
{ "city": "Milwaukee", "state": "Wisconsin" },
{ "city": "Myrtle Beach", "state": "South Carolina" },
{ "city": "Amarillo", "state": "Texas" },
{ "city": "Stockton", "state": "California" },
{ "city": "Mesa", "state": "Arizona" },
{ "city": "Seattle", "state": "Washington" },
{ "city": "Chesapeake", "state": "Virginia" },
{ "city": "South Bend", "state": "Indiana" },
{ "city": "Dallas", "state": "Texas" },
{ "city": "Kansas City", "state": "Missouri" },
{ "city": "Ventura", "state": "California" },
{ "city": "Norfolk", "state": "Virginia" },
{ "city": "Atlanta", "state": "Georgia" },
{ "city": "Kansas City", "state": "Missouri" },
{ "city": "Spokane", "state": "Washington" },
{ "city": "Troy", "state": "Michigan" },
{ "city": "Glendale", "state": "California" },
{ "city": "Phoenix", "state": "Arizona" },
{ "city": "New Orleans", "state": "Louisiana" },
{ "city": "Wichita", "state": "Kansas" },
{ "city": "Youngstown", "state": "Ohio" },
{ "city": "Baltimore", "state": "Maryland" },
{ "city": "Sacramento", "state": "California" },
{ "city": "Miami", "state": "Florida" },
{ "city": "Albuquerque", "state": "New Mexico" },
{ "city": "Monticello", "state": "Minnesota" },
{ "city": "Corpus Christi", "state": "Texas" },
{ "city": "Anchorage", "state": "Alaska" },
{ "city": "Springfield", "state": "Massachusetts" },
{ "city": "Chicago", "state": "Illinois" },
{ "city": "Simi Valley", "state": "California" },
{ "city": "Hollywood", "state": "Florida" },
{ "city": "Pensacola", "state": "Florida" },
{ "city": "Vero Beach", "state": "Florida" },
{ "city": "North Hollywood", "state": "California" },
{ "city": "Portland", "state": "Oregon" }]